// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Z4YM5U5GFE9-qKY6vhQHLxBG3gRwwaw',
    appId: '1:990778095292:web:eec4273ebf77a10b0502b9',
    messagingSenderId: '990778095292',
    projectId: 'novalab-41e12',
    authDomain: 'novalab-41e12.firebaseapp.com',
    storageBucket: 'novalab-41e12.appspot.com',
    measurementId: 'G-869S2T8ZHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_AA_m6sSrud5FeI2knersP4Kly0iCg4',
    appId: '1:990778095292:android:d81fb16817350e850502b9',
    messagingSenderId: '990778095292',
    projectId: 'novalab-41e12',
    storageBucket: 'novalab-41e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHaRiwqQE6A47vKVJoQpmUI7NgiMVjDxQ',
    appId: '1:990778095292:ios:e7b0844016f8a3120502b9',
    messagingSenderId: '990778095292',
    projectId: 'novalab-41e12',
    storageBucket: 'novalab-41e12.appspot.com',
    iosBundleId: 'com.example.novalabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHaRiwqQE6A47vKVJoQpmUI7NgiMVjDxQ',
    appId: '1:990778095292:ios:09d4e52c4d3afe000502b9',
    messagingSenderId: '990778095292',
    projectId: 'novalab-41e12',
    storageBucket: 'novalab-41e12.appspot.com',
    iosBundleId: 'com.example.novalabs.RunnerTests',
  );
}
